---
spring:
  profiles: cloud
  application:
    name: shop-service
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}config-server.credentials.uri:http://${PREFIX:}${config-server.${application.domain:cfapps.io}}}
      discovery:
        enabled: true
---

spring:
  profiles: development
  application:
    name: shop-service
  cloud:
    config:
      uri: http://localhost:8888
      discovery:
        serviceId: config-server
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    database: POSTGRESQL
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    initialize: false
    url: jdbc:postgresql://localhost:5432/shop
    username: sysadm
    password: sysadm
    driver-class-name: org.postgresql.Driver
  resources:
    chain:
      enabled: true
  cache:
    ehcache:
      config: classpath:ehcache.xml
server:
  port: 9000
eureka:
  instance:
    hostname: shop-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    nonSecurePort: ${server.port}
  client:
    eureka-connection-idle-timeout-seconds: 3000
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 18000000
  ConnectTimeout: 18000000
  eureka:
    enabled: false
encrypt:
  failOnError: false
logging:
  file: log.txt
  level: error
jwt:
  header: AuthHeader
  key: e038394bc945eed83ca8797aae26fddfae91b175fc4dd26339dd6cb8066c65b892d6ac07c0a3c0384601896ade90551905460af66e4864e9c71a31d6d523c136
  expiration: 36000
security:
  basic:
    enabled: false
---

spring:
  profiles: docker
  application:
    name: shop-service
  cloud:
    config:
      uri: http://config-server:8888
      discovery:
        serviceId: config-server
---