---
spring:
  profiles: development
  application:
    name: turbine-server
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 20
      discovery:
        serviceId: config-server
        enabled: false
      uri: https://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
info:
  component: Turbine
PREFIX:
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
management:
  port: 8990
eureka:
  instance:
    hostname: turbine-server
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    eureka-connection-idle-timeout-seconds: 3000
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
logging:
  level:
    root: WARN
    com.netflix.discovery: 'OFF'
    org.springframework.cloud.config.client.ConfigServicePropertySourceLocator: INFO
    org.springframework.retry.support.RetryTemplate: DEBUG
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO
turbine:
  amqp:
    port: 8989
server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: localhost
    trust-store: classpath:truststore.jks
    trust-store-password: password
security:
  basic:
    enabled: false
---
spring:
  profiles: cloud
  application:
    name: turbine-server
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}config-server.credentials.uri:https://${PREFIX:}${config-server.${application.domain:cfapps.io}}}
      discovery:
        service-id: config-server
      fail-fast: true
---
spring:
  profiles: docker
  application:
    name: turbine-server
  cloud:
    config:
      uri: https://config-server:8888
      discovery:
        serviceId: config-server
      fail-fast: true