---
spring:
  profiles: development
  application:
    name: eureka-service
  cloud:
    config:
      uri: https://localhost:8888
      discovery:
        serviceId: config-server
eureka:
  instance:
    hostname: eureka-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
  server:
    enable-self-preservation: false
server:
  port: 8761
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: localhost
    trust-store: classpath:truststore.jks
    trust-store-password: password
    client-auth: want
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
security:
  basic:
    enabled: false
---
spring:
  profiles: docker
  application:
    name: eureka-service
  cloud:
    config:
      uri: https://config-server:8888
      discovery:
        serviceId: config-server
      fail-fast: true
---
spring:
  profiles: cloud
  application:
    name: eureka-service
  cloud:
    config:
      uri: https://config-server-mateuszsojka.cfapps.io:8888/
      discovery:
        serviceId: config-server
      fail-fast: true