export const CLIENT_CONTEXT_CHANGED = 'CLIENT_CONTEXT_CHANGED';
export const CLIENT_CONTEXT_CHANGED_EVENT = `window:${CLIENT_CONTEXT_CHANGED}`;
export const APPLICATION_CONTEXT_CHANGED = 'APPLICATION_CONTEXT_CHANGED';
export const APPLICATION_CONTEXT_CHANGED_EVENT = `window:${APPLICATION_CONTEXT_CHANGED}`;

export const VALUE_CHANGED = 'VALUE_CHANGED';
export const VALUE_CHANGED_EVENT = `window:${VALUE_CHANGED}`;
export const EDIT_FLAG_CHANGED = 'EDIT_FLAG_CHANGED';
export const EDIT_FLAG_CHANGED_EVENT = `window:${EDIT_FLAG_CHANGED}`;
export const LOCALE_CHANGED = 'LOCALE_CHANGED';
export const LOCALE_CHANGED_EVENT = `window:${LOCALE_CHANGED}`;
